### ISSUE TITLE
High Performance Impact

### ISSUE THREAD

**Issue by JigSawFr** [anou/iftheme#1]
Hi,
There is an high performance issue due to your theme calendar module.
It's a must needs to rewrite this module or disable it.

![profilerisf_calendar](https://cloud.githubusercontent.com/assets/5781907/11805926/e4c444f0-a30f-11e5-851f-9bd66b85e4e6.PNG)

Thank you :)

**Comment by anou** [comment]
Thanks for the info.

I must say that I now work on this project freely, so I must find some time to rewrite it.

I hope before the end of this year.

Have a nice day.

/////
David Thomas
SMOL http://smol.org/ studio de création sympathique
+336 738 765 00
anou@smol.org

**Comment by JigSawFr** [comment]
No problem,
It's just an indication to show identified problem,

It's the results from my benchmark with profiler (in a dev environment)
Original theme took 5 000ms
ISF theme took 30 000ms.

Happy Holidays

**Comment by anou** [comment]
Happy holidays too ;-)

and thanks
/////
David Thomas
SMOL http://smol.org/ studio de création sympathique
+336 738 765 00
anou@smol.org
